/*
 * attr-pagertarget.idl -- test the PagerTarget operation attribute
 * Copyright 2010  Kalle A. Sandström <ksandstr@iki.fi>
 *
 * This file is part of µiX.
 *
 * µiX is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * µiX is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with µiX.  If not, see <http://www.gnu.org/licenses/>.
 */

/* AUTOTEST: ./muidl -D __TEST__=%t -I idl %n */

#include "l4x2.idl"
#include "posix-base.idl"

/* TODO: add actual autotests -- perhaps just to see if the output compiles,
 * somehow.
 */

module MuidlTest
{

interface PagerTargetTest
{
	[PagerTarget]
	void pt_op_without_params();

	[PagerTarget]
	void pt_op_with_params(in long something);

	void npt_op_without_params();

	void npt_op_with_params(in long something);
};

};
