/* this module should be compiled into any program that links either a service
 * or client implementation generated by muidl.
 *
 * it is licensed under the GNU Lesser General Public License version 3, or at
 * your option any later version of the GNU Lesser General Public License
 * published by the Free Software Foundation.
 */

#include <l4/types.h>
#include <l4/message.h>

/* returns length of stritem in @utcb starting at MR *@tpos. increments *@tpos
 * according to number of words in the string item.
 *
 * when returned *@tpos > t_last, the result is invalid. the function should
 * also not be called when *@tpos >= t_last.
 */
int __muidl_get_stritem_len(void *utcb, int *tpos)
{
	int len = 0;
	L4_StringItem_t *si = utcb + *tpos * sizeof(L4_Word_t), *prev;
	do {
		if(!L4_IsStringItem(si)) goto err;
		prev = si;
		len += si->X.string_length * L4_Substrings(si);
		*tpos += L4_Substrings(si) + 1;
		si = utcb + *tpos * sizeof(L4_Word_t);
	} while(L4_CompoundString(prev));
	return len;

err:
	*tpos += 66;
	return 0;
}
