
#ifndef SEEN_MUIDL_IDL_TRIVIAL_TEST
#define SEEN_MUIDL_IDL_TRIVIAL_TEST


[StubPrefix(__countserv)]
interface Countserv
{
	/* you may hyperventilate! */
	[Label(666)]
	long bump();

	[Label(667)]
	void set(in long value);
};


#endif
