
#ifndef SEEN_MUIDL_IDL_EXCEPT_IDL
#define SEEN_MUIDL_IDL_EXCEPT_IDL

#include "posix-base.idl"
#include "muidl.idl"


struct CompoundData
{
	short what;
	long zort;
	long poit;
};

exception TestException
{
	long something;
	octet other;
	boolean condition;
};

exception AnotherException
{
	boolean recoverable_p;
	long where;
	short what;
	CompoundData phale;
};

interface ExceptTest
{
	[Label(1)]
	void thrower()
		raises(TestException, muidl::NoReply);

	[Label(2)]
	void chucker()
		raises(muidl::NoReply);

	[Label(3)]
	void slinger(in long whatever, out short something)
		raises(muidl::NoReply, TestException, AnotherException, Posix::Errno);
};


#endif
