
#ifndef _L4X2_IDL
#define _L4X2_IDL

// make-believe IDL for L4.X2 protocols


module L4X2
{

native l4_word_t;
typedef l4_word_t word;

native l4_mapgrantitem_t;
typedef l4_mapgrantitem_t MapGrantItem;


interface FaultHandler
{
	[TagMask(0xfff00000), Label(0xff40)]
	MapGrantItem handle_fault(
		[MR(1)] in word faddr,
		[MR(2)] in word fip);
};

}; // module

#endif
