
#ifndef _L4X2_IDL
#define _L4X2_IDL

/* FIXME: remove this, it doesn't belong here for real */
#include "posix-base.idl"

// make-believe IDL for L4.X2 protocols


module L4X2
{

native l4_word_t;
typedef l4_word_t word;

native l4_mapgrantitem_t;
typedef l4_mapgrantitem_t MapGrantItem;

native l4_fpage_t;
typedef l4_fpage_t Fpage;


interface FaultHandler
{
	[TagMask(0xfff00000), Label(0xff40)]
	MapGrantItem handle_fault(
		[MR(1)] in word faddr,
		[MR(2)] in word fip);

	/* these only exist for test's sake, move them out at some point */
	[Label(0xface)]
	void void_operation(in word foo, in word bar)
		raises(Posix::Errno);

	[Label(0xfacf)]
	unsigned short ushort_operation(in word foo, in unsigned short mask)
		raises(Posix::Errno);

	[Label(0xfad0)]
	octet octet_operation(in word foo, inout octet mask)
		raises(Posix::Errno);

	[Label(0xfad1)]
	void outsy_operation(in word foo, out word bar);
};

}; // module

#endif
