
#ifndef SEEN_MUIDL_IDL_MAPPING_IDL
#define SEEN_MUIDL_IDL_MAPPING_IDL

#include "posix-base.idl"
#include "muidl.idl"


interface MappingTest
{
	[Label(1)]
	void put_memory(in long what, in muidl::mapping map);

	[Label(2)]
	void get_memory(in long what, out muidl::mapping the_thing);
};

#endif
