
#ifndef SEEN_MUIDL_STRINGSERV_IDL
#define SEEN_MUIDL_STRINGSERV_IDL

#include <posix-base.idl>

[StubPrefix(__stringserv)]
interface Stringserv
{
	[Label(5)]
	void print_string(in string<128> boring_message);

	[Label(23)]
	void log_string(
		in string<32> log_id,
		in string<128> boring_message);


	struct small {
		boolean first, second;
		octet third;
		short fourth;
	};

	[Label(42)]
	void log_with_id(
		in long identifier,
		in string<128> whatever_dude,
		out long woord,
		out small something);

	struct tiny {
		octet what;
		boolean how;
	};

	[Label(43)]
	void log_with_id_aaaannnnd(
		in long id,
		in string<128> w_e,
		out long whot,
		out tiny miniscule);

	exception StringyException {
		string<40> longer_string;
		string<16> shorter_string;
	};

	[Label(44)]
	void get_displaced_things(
		in long identifier,
		out string<32> short_string,
		out string<64> longer_string)
			raises(StringyException);

#if 0
	typedef sequence<short, 300> shortseq;

	[Label(69)]
	void eat_my_shorts(in shortseq trousers);
#endif
};


#endif
